name: "Build and deploy"
description: "Build and deploy"
inputs:
  type:
    description: "branch, release"
    required: true
  skerootca:
    description: "root ca"
    required: true
  image-name:
    description: "build image name"
    required: true
  nexus-user:
    description: "Nexus username"
    required: true
  nexus-pass:
    description: "Nexus password"
    required: true
  github-token:
    description: "Github token"
    required: true
  sonarqube-token:
    description: "sonarqube-token"
    required: true
  sonarqube-host:
    description: "sonarqube-token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Hent versjon
      id: version
      uses: skatteetaten-it/mvn-composite-action/version@main
      with:
        type: ${{ inputs.type }}
    - name: Maven setup
      uses: skatteetaten-it/mvn-composite-action/setup@v1
      with:
        skerootca: ${{ inputs.skerootca }}

    - name: Build with maven
      env:
        NEXUS_USER: ${{ inputs.nexus-user }}
        NEXUS_PASS: ${{ inputs.nexus-pass }}
        GITHUB_TOKEN: ${{ inputs.github-token }} # Needed to get PR information, if any
      run: mvn -U -B verify
      shell: bash
    - name: Sonar
      if: contains(github.ref, '/dependabot/') != true
      env:
        NEXUS_USER: ${{ inputs.nexus-user }}
        NEXUS_PASS: ${{ inputs.nexus-pass }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: mvn sonar:sonar -Dsonar.projectVersion=${{ steps.version.outputs.version }} -Dsonar.branch.name=${{ github.github.ref_name	 }} -Dsonar.login=${{ inputs.sonarqube-token }} -e -Dsonar.host.url=${{ inputs.sonarqube-host }}  -B
      shell: bash

    - name: Test report
      if: contains(github.ref, '/dependabot/') != true
      uses: skatteetaten-it/mvn-composite-action/test-report@v1

    - name: Deploy
      if: contains(github.ref, '/dependabot/') != true
      uses: skatteetaten-it/mvn-composite-action/deploy@v1
      with:
        nexus-user: ${{ inputs.nexus-user }}
        nexus-pass: ${{ inputs.nexus-pass }}
        github-token: ${{ inputs.github-token }}
        image-name: ${{ inputs.image-name }}::${{ steps.version.outputs.version }}
