name: "Build and deploy"
description: "Build and deploy"
inputs:
  type:
    description: "branch, release"
    required: true
  skerootca:
    description: "root ca"
    required: true
  image-name:
    description: "build image name"
    required: false
  nexus-user:
    description: "Nexus username"
    required: true
  nexus-pass:
    description: "Nexus password"
    required: true
  github-token:
    description: "Github token"
    required: true
  sonarqube-token:
    description: "sonarqube-token"
    required: true
  nexusiq-username:
    description: "nexusiq-username"
    required: true
  nexusiq-password:
    description: "nexusiq-password"
    required: true
  nexusiq-applicationid:
    description: "nexusiq-applicationid"
    required: true
  java-version:
    description: "Java version"
    required: false
    default: 17
  working-directory:
    description: "Working directory"
    required: false
    default: "."
  build-docker-image:
    description: "Build docker image"
    required: false
    default: true
  jacoco-csv-file:
    description: "Overstyr jacoco csv fil"
    required: false
    default: target/site/jacoco/jacoco.csv
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get version
      id: version
      uses: skatteetaten-it/mvn-composite-action/version@feature/run_number
      with:
        type: ${{ inputs.type }}
    - name: Maven setup
      uses: skatteetaten-it/mvn-composite-action/setup@v2
      with:
        skerootca: ${{ inputs.skerootca }}
        java-version: ${{ inputs.java-version }}
        working-directory: ${{ inputs.working-directory}}

    - name: Build with maven
      env:
        NEXUS_USER: ${{ inputs.nexus-user }}
        NEXUS_PASS: ${{ inputs.nexus-pass }}
        GITHUB_TOKEN: ${{ inputs.github-token }} # Needed to get PR information, if any
      working-directory: ${{ inputs.working-directory}}
      run: mvn -U -B verify -Duser.timezone=CET -U
      shell: bash
    - name: Nexus IQ Policy Evaluation
      if: contains(github.ref, '/dependabot/') != true
      uses: sonatype-nexus-community/iq-github-action@1.1.0
      with:
        serverUrl: https://iq.aurora.skead.no/
        username: ${{ inputs.nexusiq-username }}
        password: ${{ inputs.nexusiq-password }}
        applicationId: ${{ inputs.nexusiq-applicationid }}
        stage: ${{ inputs.type == 'release' && 'Release' || 'Build' }}
        target: ${{ inputs.working-directory}}/target/
    - name: Sonar
      if: contains(github.ref, '/dependabot/') != true
      env:
        NEXUS_USER: ${{ inputs.nexus-user }}
        NEXUS_PASS: ${{ inputs.nexus-pass }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      working-directory: ${{ inputs.working-directory}}
      run: mvn sonar:sonar -Dsonar.projectVersion=${{ steps.version.outputs.version }} -Dsonar.branch.name=${{ inputs.type == 'release' && 'main' || github.ref_name }} -Dsonar.login=${{ inputs.sonarqube-token }} -e -Dsonar.host.url=https://sonar.aurora.skead.no/   -B
      shell: bash

    - name: Test report
      if: contains(github.ref, '/dependabot/') != true
      uses: skatteetaten-it/mvn-composite-action/test-report@v2
      with:
        working-directory: ${{ inputs.working-directory}}
        jacoco-csv-file: ${{ inputs.jacoco-csv-file}}

    - name: Deploy
      if: contains(github.ref, '/dependabot/') != true
      uses: skatteetaten-it/mvn-composite-action/deploy@v2
      with:
        working-directory: ${{ inputs.working-directory}}
        nexus-user: ${{ inputs.nexus-user }}
        nexus-pass: ${{ inputs.nexus-pass }}
        github-token: ${{ inputs.github-token }}
        build-docker-image: ${{ inputs.build-docker-image }}
        image-name: ${{ inputs.image-name }}:${{ steps.version.outputs.version }}
        mvnversion: ${{ steps.version.outputs.mvnversion }}
