name: "Sonar med jacoco"
description: "Greet someone"
inputs:
  jacoco-csv-file:
    description: "Overstyr jacoco csv fil"
    required: false
runs:
  using: "composite"
  steps:
    - name: Build with Maven
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST}}
      run: mvn -U -B verify sonar:sonar --fail-at-end
      shell: bash

    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: ${{ inputs.jacoco-csv-file }}

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      shell: bash

    - name: Commit and push the badge (if it changed)
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: "[ci skip] commit badge"
        add: "*.svg"

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
