name: "Test rapport"
description: "Test rapport med jacoco"
inputs:
  jacoco-csv-file:
    description: "Overstyr jacoco csv fil"
    required: false
    default: target/site/jacoco/jacoco.csv
runs:
  using: "composite"
  steps:
    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1

    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        jacoco-csv-file: ${{ inputs.jacoco-csv-file }}

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
        echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      shell: bash

    - name: Commit and push the badge (if it changed)
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: "[ci skip] commit badge"
        add: "*.svg"

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path:  target/site/jacoco/
