name: "Deploy"
description: "Deploy"
inputs:
  image-name:
    description: "build image name"
    required: true
  nexus-user:
    description: "Nexus username"
    required: true
  nexus-pass:
    description: "Nexus password"
    required: true
  github-token:
    description: "Github token"
    required: true
  working-directory:
    description: "Working directory"
    required: false
    default: "."
  build-docker-image:
    description: "Build docker image"
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Set version
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
      working-directory: ${{ inputs.working-directory}}
      run: mvn -U -B versions:set -DnewVersion=${{ steps.prep.outputs.mvnversion }}
      shell: bash
    - name: deploy maven image
      env:
        NEXUS_USER: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASS: ${{ secrets.NEXUS_PASSWORD }}
      working-directory: ${{ inputs.working-directory}}
      run: mvn  -DskipTests=true deploy -Duser.timezone=CET -U
      shell: bash
    - name: Build dockerimage
      if: ${{ inputs.build-docker-image}}
      env:
        NEXUS_USER: ${{ inputs.nexus-user }}
        NEXUS_PASS: ${{ inputs.nexus-pass }}
      working-directory: ${{ inputs.working-directory}}
      run: mvn -U -B -DskipTests=true spring-boot:build-image -Dspring-boot.build-image.imageName=${{ inputs.image-name }}
      shell: bash

    - name: Login to GitHub Container Registry
      if: ${{ inputs.build-docker-image}}
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github-token }}

    - name: "push image"
      if: ${{ inputs.build-docker-image}}
      run: docker push ${{ inputs.image-name }}
      shell: bash
