name: "Maven setup med nexus"
description: "Greet someone"
inputs:
  skerootca:
    description: "root sertifikat"
    required: true
  skerootca-prosjekter:
    description: "Prosjekter, settes om det er en multi pom"
    required: false
  java-versjon:
    description: "Java versjon"
    required: false
    default: 11
runs:
  using: "composite"
  steps:
    - name: skerootca
      env:
        SKEROOTCA: ${{ inputs.skerootca }}
      run: ${{ github.action_path }}/skerootca.sh ${{ inputs.skerootca-prosjekter }}
      shell: bash
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java-versjon }}
        distribution: "temurin"
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.8.2

    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v18
      with:
        servers: >
          [
          { "id": "nexus", "username": "${env.NEXUS_USER}", "password": "${env.NEXUS_PASS}" },
          { "id": "snapshots", "username": "${env.NEXUS_USER}", "password": "${env.NEXUS_PASS}" },
          { "id": "releases", "username": "${env.NEXUS_USER}", "password": "${env.NEXUS_PASS}" }
          ]
        mirrors: >
          [{ "id": "nexus", "mirrorOf": "*", "name": "Aurora Nexus", "url": "https://nexus.sits.no/repository/maven-intern" }]
        repositories: >
          [{ "id": "central", "url": "http:/central", "releases": {"enabled": "true"}, "snapshots": {"enabled": "true"} }]
        plugin_repositories: >
          [{ "id": "central", "url": "http:/central", "releases": {"enabled": "true"}, "snapshots": {"enabled": "true"} }]
    - name: setup cache
      id: cache
      run: mkdir -p /cache/repository; ln -sfn /cache/repository /home/runner/.m2/repository
      shell: bash
